services:

    _defaults:
        public: true

    webfactory_wfd_meta.doctrine_metadata_helper:
        alias: 'Webfactory\Bundle\WfdMetaBundle\DoctrineMetadataHelper'
        deprecated: ~

    webfactory_wfd_meta.provider:
        alias: 'Webfactory\Bundle\WfdMetaBundle\Provider'
        deprecated: ~

    webfactory_wfd_meta.metadata_facade:
        alias: 'Webfactory\Bundle\WfdMetaBundle\MetadataFacade'
        deprecated: ~

    webfactory_wfd_meta.meta_query_factory:
        alias: 'Webfactory\Bundle\WfdMetaBundle\MetaQueryFactory'
        deprecated: ~

    webfactory_wfd_meta.meta_query:
        alias: 'Webfactory\Bundle\WfdMetaBundle\MetaQuery'
        deprecated: ~

    webfactory_wfd_meta.caching.event_listener:
        alias: 'Webfactory\Bundle\WfdMetaBundle\Caching\EventListener'
        deprecated: ~

    webfactory_wfd_meta.controller.template:
        alias: 'Webfactory\Bundle\WfdMetaBundle\Controller\TemplateController'
        deprecated: ~

    webfactory_wfd_meta.config_cache_factory:
        alias: 'Webfactory\Bundle\WfdMetaBundle\Config\WfdMetaConfigCacheFactory'
        deprecated: ~
